name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: build storybook-static
        run: npm run storybook:build
        if: always()
      - name: snapshot testing
        run: npm run test:ui:ci
        if: always()

